[package]
name = "op-move"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
aptos-types = { git = "https://github.com/aptos-labs/aptos-core" }
bcs = { git = "https://github.com/aptos-labs/bcs" }
ethers-core = "2.0"
flate2 = "1"
hex = "0.4"
hyper = "0.14"
move-core-types = { git = "https://github.com/aptos-labs/aptos-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
warp-reverse-proxy = "1"

[patch.crates-io]
x25519-dalek = { git = "https://github.com/aptos-labs/x25519-dalek", branch = "zeroize_v1" }
