services:
  foundry:
    image: ghcr.io/uminetwork/foundry:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.foundry
      cache_from:
        - type=registry,ref=ghcr.io/uminetwork/foundry:latest-cache,mode=max
      cache_to:
        - type=registry,ref=ghcr.io/uminetwork/foundry:latest-cache,mode=max
    deploy:
      replicas: 0

  optimism:
    image: ghcr.io/uminetwork/optimism:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.optimism
      additional_contexts:
        ghcr.io/uminetwork/foundry: "service:foundry"
      cache_from:
        - type=registry,ref=ghcr.io/uminetwork/optimism:latest-cache,mode=max
      cache_to:
        - type=registry,ref=ghcr.io/uminetwork/optimism:latest-cache,mode=max
    depends_on:
      - foundry
    deploy:
      replicas: 0
    networks:
      - localnet

  op-node:
    image: ghcr.io/uminetwork/op-node:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.op-node
      additional_contexts:
        ghcr.io/uminetwork/optimism: "service:optimism"
        ghcr.io/uminetwork/foundry: "service:foundry"
      cache_from:
        - type=registry,ref=ghcr.io/uminetwork/op-node:latest-cache,mode=max
      cache_to:
        - type=registry,ref=ghcr.io/uminetwork/op-node:latest-cache,mode=max
    environment:
      JWT_SECRET: "f3099a1d969c4f5aba1a94434c368a84f8d950121feb4a398a67f78453853d1d"
    networks:
      - localnet
    depends_on:
      - optimism
      - foundry
    volumes:
      - ./docker/volumes/shared:/volume/shared

  op-batcher:
    image: ghcr.io/uminetwork/op-batcher:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.op-batcher
      additional_contexts:
        ghcr.io/uminetwork/optimism: "service:optimism"
        ghcr.io/uminetwork/foundry: "service:foundry"
      cache_from:
        - type=registry,ref=ghcr.io/uminetwork/op-batcher:latest-cache,mode=max
      cache_to:
        - type=registry,ref=ghcr.io/uminetwork/op-batcher:latest-cache,mode=max
    networks:
      - localnet
    depends_on:
      - optimism
      - foundry
    volumes:
      - ./docker/volumes/shared:/volume/shared

  op-proposer:
    image: ghcr.io/uminetwork/op-proposer:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.op-proposer
      additional_contexts:
        ghcr.io/uminetwork/optimism: "service:optimism"
        ghcr.io/uminetwork/foundry: "service:foundry"
      cache_from:
        - type=registry,ref=ghcr.io/uminetwork/op-proposer:latest-cache,mode=max
      cache_to:
        - type=registry,ref=ghcr.io/uminetwork/op-proposer:latest-cache,mode=max
    networks:
      - localnet
    depends_on:
      - optimism
      - foundry
    volumes:
      - ./docker/volumes/shared:/volume/shared

  op-geth:
    image: ghcr.io/uminetwork/op-geth:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.op-geth
      additional_contexts:
        ghcr.io/uminetwork/optimism: "service:optimism"
        ghcr.io/uminetwork/foundry: "service:foundry"
      cache_from:
        - type=registry,ref=ghcr.io/uminetwork/op-geth:latest-cache,mode=max
      cache_to:
        - type=registry,ref=ghcr.io/uminetwork/op-geth:latest-cache,mode=max
    environment:
      JWT_SECRET: "f3099a1d969c4f5aba1a94434c368a84f8d950121feb4a398a67f78453853d1d"
    networks:
      - localnet
    depends_on:
      - optimism
      - foundry
    volumes:
      - ./docker/volumes/shared:/volume/shared

  op-move:
    image: ghcr.io/uminetwork/op-move:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.op-move
      cache_from:
        - type=registry,ref=ghcr.io/uminetwork/op-move:latest-cache,mode=max
      cache_to:
        - type=registry,ref=ghcr.io/uminetwork/op-move:latest-cache,mode=max
    environment:
      OP_MOVE_AUTH_JWT_SECRET: "f3099a1d969c4f5aba1a94434c368a84f8d950121feb4a398a67f78453853d1d"
      OP_MOVE_DB_PURGE: ${OP_MOVE_DB_PURGE:-false}
      OP_GETH_ADDR: "op-geth"
    networks:
      - localnet
    volumes:
      - ./docker/volumes/shared:/volume/shared
      - ./docker/volumes/db:/volume/db
    ports:
      - "8545:8545"
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://0.0.0.0:8545/',
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  geth:
    image: ghcr.io/uminetwork/geth:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.geth
      additional_contexts:
        ghcr.io/uminetwork/foundry: "service:foundry"
      cache_from:
        - type=registry,ref=ghcr.io/uminetwork/geth:latest-cache,mode=max
      cache_to:
        - type=registry,ref=ghcr.io/uminetwork/geth:latest-cache,mode=max
    networks:
      - localnet
    depends_on:
      - foundry
    ports:
      - "58138:58138"

networks:
  localnet:
    external: true
