services:
  foundry:
    image: umi-foundry:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.foundry
    deploy:
      replicas: 0

  optimism:
    image: umi-optimism:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.optimism
    depends_on:
      - foundry
    deploy:
      replicas: 0
    networks:
      - localnet

  op-node:
    image: umi-op-node:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.op-node
    environment:
      JWT_SECRET: "f3099a1d969c4f5aba1a94434c368a84f8d950121feb4a398a67f78453853d1d"
    networks:
      - localnet
    depends_on:
      - optimism
      - foundry
    volumes:
      - ./docker/volumes/shared:/volume/shared

  op-batcher:
    image: umi-op-batcher:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.op-batcher
    networks:
      - localnet
    depends_on:
      - optimism
      - foundry
    volumes:
      - ./docker/volumes/shared:/volume/shared

  op-proposer:
    image: umi-op-proposer:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.op-proposer
    networks:
      - localnet
    depends_on:
      - optimism
      - foundry
    volumes:
      - ./docker/volumes/shared:/volume/shared

  op-geth:
    image: umi-op-geth:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.op-geth
    environment:
      JWT_SECRET: "f3099a1d969c4f5aba1a94434c368a84f8d950121feb4a398a67f78453853d1d"
    networks:
      - localnet
    depends_on:
      - optimism
      - foundry
    volumes:
      - ./docker/volumes/shared:/volume/shared

  op-move:
    image: umi-op-move:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.op-move
    environment:
      OP_MOVE_AUTH_JWT_SECRET: "f3099a1d969c4f5aba1a94434c368a84f8d950121feb4a398a67f78453853d1d"
      OP_MOVE_DB_PURGE: ${OP_MOVE_DB_PURGE:-false}
      OP_GETH_ADDR: "op-geth"
    networks:
      - localnet
    depends_on:
      - op-node
    volumes:
      - ./docker/volumes/shared:/volume/shared
      - ./docker/volumes/db:/volume/db
    ports:
      - "8545:8545"
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://0.0.0.0:8545/',
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  geth:
    image: umi-geth:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.geth
    networks:
      - localnet
    depends_on:
      - foundry
    ports:
      - "58138:58138"

networks:
  localnet:
    external: true
