services:
  optimism:
    build:
      cache_from:
        - type=registry,ref=ghcr.io/uminetwork/optimism:latest-cache
      cache_to:
        - type=registry,ref=ghcr.io/uminetwork/optimism:latest-cache,mode=max

  op-node:
    build:
      cache_from:
        - type=registry,ref=ghcr.io/uminetwork/op-node:latest-cache
      cache_to:
        - type=registry,ref=ghcr.io/uminetwork/op-node:latest-cache,mode=max
      additional_contexts:
        optimism: "docker-image://ghcr.io/uminetwork/optimism:latest"

  op-batcher:
    build:
      cache_from:
        - type=registry,ref=ghcr.io/uminetwork/op-batcher:latest-cache
      cache_to:
        - type=registry,ref=ghcr.io/uminetwork/op-batcher:latest-cache,mode=max
      additional_contexts:
        optimism: "docker-image://ghcr.io/uminetwork/optimism:latest"

  op-proposer:
    build:
      cache_from:
        - type=registry,ref=ghcr.io/uminetwork/op-proposer:latest-cache
      cache_to:
        - type=registry,ref=ghcr.io/uminetwork/op-proposer:latest-cache,mode=max
      additional_contexts:
        optimism: "docker-image://ghcr.io/uminetwork/optimism:latest"

  op-move:
    build:
      cache_from:
        - type=registry,ref=ghcr.io/uminetwork/op-move:latest-cache
      cache_to:
        - type=registry,ref=ghcr.io/uminetwork/op-move:latest-cache,mode=max

  geth:
    build:
      cache_from:
        - type=registry,ref=ghcr.io/uminetwork/geth:latest-cache
      cache_to:
        - type=registry,ref=ghcr.io/uminetwork/geth:latest-cache,mode=max
      additional_contexts:
        optimism: "docker-image://ghcr.io/uminetwork/optimism:latest"
