[package]
name = "umi-server-args"
description = "Umi execution HTTP server settings"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
toml.workspace = true
serde.workspace = true
thiserror.workspace = true
