[package]
name = "L2CrossDomainMessenger"
version = "1.0.0"

[addresses]
aptos_framework = "0x1"
Evm = "0x1"
L2CrossDomainMessenger = "0x4200000000000000000000000000000000000007"

[dependencies]
AptosFramework = { local = "../../../target/aptos-core/aptos-move/framework/aptos-framework/" }
Evm = { local = "../evm/" }
