[package]
name = "EthToken"
version = "1.0.0"

[addresses]
aptos_framework = "0x1"
EthToken = "0x1"

[dependencies]
AptosFramework = { local = "../../../target/aptos-core/aptos-move/framework/aptos-framework/" }
