name: Build And Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env: 
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build And Run Tests
    runs-on: macos-latest
    steps:
      # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v4.1.7
      # Set up the Rust toolchain
    - name: Set Up Rust Toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
        profile: minimal
        override: true
      # Install dependencies
    - name: Install Dependencies
      run: cargo fetch
      # Bulild and run tests, skipping integration tests
    - name: Run Tests
      run: cargo test -- --skip integration
