name: Deploy

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Free up disk space
        run: rm -rf /opt/hostedtoolcache
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Log in to the registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Set up Docker Buildx # Driver that supports cache export
        uses: docker/setup-buildx-action@v3
      - name: Pull images
        run: docker compose pull
        continue-on-error: true
      - name: Build images
        run: docker compose build
      - name: Push images
        run: docker compose push
