name: Integration

on:
  schedule:
    - cron: '0 4 * * *' # Run at 4 am UTC or around midnight EST
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  integration:
    name: Integration
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Free up disk space
        run: rm -rf /opt/hostedtoolcache
      - name: Generate keystore file
        run: . docker/keystore.sh
      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run container images
        run: |
          docker network create localnet
          # Meant for workflow dispatch with local changes to the image
          if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
            echo "Building images locally for feature branch..."
            docker compose build
            docker compose up -d
          else
            echo "Using registry images..."
            docker compose pull
            docker compose up -d
          fi

      - name: Run integration test
        run: cargo test --release test_on_ethereum
      - name: Capture logs
        uses: jwalton/gh-docker-logs@v2
        with:
          dest: './logs'
      - name: Upload logs
        uses: actions/upload-artifact@master
        with:
          name: logs
          path: ./logs
