name: Integration

on:
  schedule:
    - cron: '0 4 * * *' # Run at 4 am UTC or around midnight EST
  workflow_dispatch:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  integration:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          default: true
          toolchain: stable
      - name: Free up disk space
        run: rm -rf /opt/hostedtoolcache
      - name: Generate keystore file
        run: . docker/keystore.sh
      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run container
        run: |
          docker pull ghcr.io/uminetwork/foundry
          docker pull ghcr.io/uminetwork/geth
          docker pull ghcr.io/uminetwork/optimism
          docker pull ghcr.io/uminetwork/op-geth
          docker pull ghcr.io/uminetwork/op-node
          docker pull ghcr.io/uminetwork/op-batcher
          docker pull ghcr.io/uminetwork/op-proposer
          docker pull ghcr.io/uminetwork/op-move
          . docker/host/deploy.sh

      - name: Sleep for 10 minutes
        run: sleep 10m
      - name: Run integration test
        run: cargo test --release test_on_ethereum
      - name: Save logs
        uses: actions/upload-artifact@v4
        with:
          name: Logs
          path: server/*.log
