name: Integration

on:
  schedule:
    - cron: '0 4 * * *' # Run at 4 am UTC or around midnight EST
  workflow_dispatch:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  integration:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          default: true
          toolchain: stable
      - name: Free up disk space
        run: rm -rf /opt/hostedtoolcache

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          service_account: github-ci@your-project.iam.gserviceaccount.com
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Download files from Google Cloud Storage
        run: | 
          gcloud storage cp -r gs://integration-test-binaries/* /usr/local/bin/
          chmod +x /usr/local/bin/geth /usr/local/bin/op-*

      - name: Debug_List_Files
        run: ls -al /usr/local/bin/
#      - name: Integration test
#        run: cargo test --release test_on_ethereum
      - name: Mock log files
        run: |
          echo "test geth" > server/geth.log
          echo "test op-batcher" > server/op_batcher.log
          echo "test op-geth" > server/op_geth.log
          echo "test op-node" > server/op_node.log
          echo "test op-proposer" > server/op_proposer.log
      - uses: actions/upload-artifact@v4
        with:
          name: Logs
          path: server/*.log
