name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Set up Rust
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install dependencies
      run: cargo fetch

    - name: Run tests
      run: cargo test -- --skip integration