name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rust_test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          default: true
          toolchain: stable
      - name: Run tests
        run: cargo test